name: package_get
description: 拉取依赖管理
version: 0.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 状态管理框架
  get: 4.0.0
  # 权限申请
  permission_handler: ^8.3.0
  flutter_image_compress:
  # 获取路径
  path_provider:
  # 包信息
  package_info: ^2.0.2
  # 吐司
  bot_toast: ^4.0.1
  # 地址跳转
  url_launcher: ^6.0.10
  # 网络请求
  dio: ^4.0.4
  # 手写板
  signature: ^4.1.1
  # tab 选项卡
#  toggle_switch: ^1.3.0
  # switch 滑动按钮
  flutter_switch: ^0.3.2
  # 轮播图
  flutter_swiper_null_safety: ^1.0.2
  # 调试HTTP请求
#  dio_log:
  # 调试HTTP请求
  #  alice: ^0.2.1
  # 本地持久化
  shared_preferences: ^2.0.7
  # 日期时间格式化
  date_format: ^2.0.4
  # 拍摄
  image_picker: ^0.8.4+1
  # 上拉下拉
  flutter_easyrefresh: ^2.2.1
  # 密码、验证码输入框
  pin_code_text_field: ^1.8.0
  # 下拉筛选
  menu_button: ^1.4.2+1
  # 展示html
#  flutter_widget_from_html: 0.6.0
  flutter_html:
  # 模态加载框
  #  modal_progress_hud: ^0.1.3
  loading_overlay: ^0.3.0
  # 生成二维码
  qr_flutter: ^4.0.0
  # 图片保存
  image_gallery_saver: ^1.7.1
  # 城市三级联动选择
  city_pickers: ^1.0.1
  #  flutter_pickers: ^2.0.1
  # 仿微信左滑
#  left_scroll_actions: ^1.5.3
  # 网页显示
#  webview_flutter: ^2.0.13
  # 类似微信消息长安菜单
  custom_pop_up_menu: 1.2.3+1
  #微信图片选择器
  #  wechat_assets_picker: 6.1.2
  #微信拍照
  #  wechat_camera_picker: ^2.5.0
  # 拼音
  lpinyin: ^2.0.3
  # 图片缓存
  cached_network_image: ^3.1.0+1
  # 查看大图custom_pop_up_menu
  photo_view: 0.13.0
  # 网络连通检查
  connectivity_plus: 1.0.1
  # JSOn 格式化打印
  pretty_json: ^2.0.0
  # icon
#  font_awesome_flutter: ^9.2.0
  # 自定义tab
#  flutter_custom_tab_bar: ^1.0.6
  # 友盟
#  umeng_common_sdk: ^1.2.4
  # 腾讯异常上报
  flutter_bugly: ^0.4.3
  # 相机拍照、相册选择
  image_pickers: ^2.0.0+1
  # 中国城市选择器
  city_picker_china: ^0.0.2
  # loading模态框
  flutter_easyloading: ^3.0.3
  # 底部划出 日期选择器
  flutter_datetime_picker: ^1.5.1
  # ios 风格日期时间选择器
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_math_fork: ^0.5.0
  #本地轻量级数据缓存
  flustars:
  # 通讯录选择
  azlistview: ^2.0.0-nullsafety.0
  # 扫二维码
  flutter_qr_reader: ^1.0.5-nullsafety.1
  # 聊天气泡
  bubble_box: ^0.5.1
  # 音频播放
  flutter_audio_recorder2:
  # 录音
  flutter_sound: ^8.5.0
  # 七牛
  qiniu_flutter_sdk: ^0.3.0
  # 高德定位
  fl_amap:
  # 微信支付、微信登录、微信分享
  fluwx: 3.3.2
  # 支付宝支付、支付宝登录
  tobias:
  # 融云
  rongcloud_im_plugin: ^5.1.6+1
  # bus通知订阅
  event_bus: ^2.0.0
  # 视频播放器
  fijkplayer: ^0.10.1
  fijkplayer_skin: ^2.2.8
#  chewie: ^1.2.2
#  flutter_spinkit: ^5.1.0
#  video_player: any
#  better_player: ^0.0.62
  # 仿淘宝、京东 地址选择
  #  flutter_city_picker: ^1.0.2
  # 仿淘宝、京东 地址选择
  #  xyz_city_picker: ^1.0.1
  # 图片选择器
  #  advance_image_picker: ^0.1.2
  #  images_picker: ^1.0.0
  # 查看大图
  flutter_show_img_package:
    git:
      url: https://gitee.com/jq_flutter/flutter_show_img_package
      ref: null_safety
#  flutter_webview_plugin: ^0.4.0
  # 支持web端的webview
  webviewx: ^0.2.1
  adaptive_action_sheet: ^2.0.1
#  flutter_widget_from_html_core:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
